<a href="https://colab.research.google.com/github/carlos-douglasgauto/Python_Analise_planilhas/blob/main/Condor_planilhas_Aereo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1- Ler os Arquivos

2- olhar melhor quem são as colunas deste dataframe e começar a ter os insights de como estes dados estão distribuídos (nomedataframe.columns.values)

3- separar as colunas de interesse e colocar dentro de um dataframe que tem o nome de "selecionado" com somente as colunas que me interessam neste momento (método filter)
  (nomedataframe.filter e como parâmetro deste método (items) esta lista de colunas)

In [869]:
import pandas as pd
import numpy as np
import glob
import matplotlib.pyplot as plt

In [870]:
#ler planilhas
df_stur = pd.read_excel("/content/stur.xlsx", skiprows=[0])
df_wts = pd.read_excel("/content/wts.xls")
df_autorizador = pd.read_excel("/content/MATRICULAS FURNAS.xls")

In [871]:
df_autorizador['AUTORIZADOR'] = df_autorizador['AUTORIZADOR'].apply(lambda _: str(_))

In [872]:
#df_stur['num_ped1'] = pd.to_numeric(df_stur['num_ped1'])

In [873]:
#df_stur['num_ped1'] = pd.to_numeric(df_stur['num_ped1'])

In [874]:
df_autorizador['Nome_Autorizador'] = df_autorizador['AUTORIZADOR'].str[:20]
df_autorizador.head()

  CÓDIGO_AUTORIZADOR                        AUTORIZADOR      Nome_Autorizador
0              22659              ABEL DE JESUS FORMOSO  ABEL DE JESUS FORMOS
1              23008  ABILIO JOSE DA ROCHA REIS CARDOSO  ABILIO JOSE DA ROCHA
2              22321               ABIRAN FIALHO FOGACA  ABIRAN FIALHO FOGACA
3              23086        ABNER AUGUSTO PACHECO PIRES  ABNER AUGUSTO PACHEC
4              19988            ADAILTON MENDES MACHADO  ADAILTON MENDES MACH

In [875]:
#colunas que estão com os ítens selecionados
colunas_selecionadas_aut = ['CÓDIGO_AUTORIZADOR', 'Nome_Autorizador']

In [876]:
#filtra e organiza os dados pelas colunas que foram passadas
df_autorizador = df_autorizador.filter(items=colunas_selecionadas_aut)
df_autorizador.head()

  CÓDIGO_AUTORIZADOR      Nome_Autorizador
0              22659  ABEL DE JESUS FORMOS
1              23008  ABILIO JOSE DA ROCHA
2              22321  ABIRAN FIALHO FOGACA
3              23086  ABNER AUGUSTO PACHEC
4              19988  ADAILTON MENDES MACH

In [877]:
# 1) ler Arquivos CSV
#Rhotel_csv = pd.read_csv("/content/hotel.csv", sep=";", encoding='ISO-8859-1')

In [878]:
#usando o sinal de +
df_trecho = pd.DataFrame(df_wts,columns=['LOCALIZADOR', 'DATA_APROVACAO', 'BILHETE', 'TRECHOS',
       'TRECHOS_CIDADE', 'TOTAL_TARIFA', 'TOTAL_TAXA_EMBARQUE',
       'OUTROS_VALORES', 'TOTAL_GERAL', 'TOTAL_PAGO', 'EMISSÃO/REEMISSÃO',
       'ORIGEM1', 'DESTINO1', 'DATA_PARTIDA1', 'DATA_CHEGADA1', 'TARIFA1',
       'TARIFA_SEM_ACORDO1', 'TARIFA_ALTERNATIVA1', 'DATA_ALTERNATIVA1',
       'TAXA_EMBARQUE1', 'VOO1', 'MAIOR_TARIFA1', 'MENOR_TARIFA1',
       'ORIGEM2', 'DESTINO2', 'DATA_PARTIDA2', 'DATA_CHEGADA2',
       'TARIFA_SEM_ACORDO2', 'TARIFA2', 'TARIFA_ALTERNATIVA2',
       'DATA_ALTERNATIVA2', 'TAXA_EMBARQUE2', 'VOO2', 'MAIOR_TARIFA2',
       'MENOR_TARIFA2', 'ORIGEM3', 'DESTINO3', 'DATA_PARTIDA3',
       'DATA_CHEGADA3', 'TARIFA_SEM_ACORDO3', 'TARIFA3',
       'TARIFA_ALTERNATIVA3', 'DATA_ALTERNATIVA3', 'TAXA_EMBARQUE3',
       'VOO3', 'MAIOR_TARIFA3', 'MENOR_TARIFA3', 'ORIGEM4', 'DESTINO4',
       'DATA_PARTIDA4', 'DATA_CHEGADA4', 'TARIFA_SEM_ACORDO4', 'TARIFA4',
       'TARIFA_ALTERNATIVA4', 'DATA_ALTERNATIVA4', 'TAXA_EMBARQUE4',
       'VOO4', 'MAIOR_TARIFA4', 'MENOR_TARIFA4', 'ORIGEM5', 'DESTINO5',
       'DATA_PARTIDA5', 'DATA_CHEGADA5', 'TARIFA_SEM_ACORDO5', 'TARIFA5',
       'TARIFA_ALTERNATIVA5', 'DATA_ALTERNATIVA5', 'TAXA_EMBARQUE5',
       'VOO5', 'MAIOR_TARIFA5', 'MENOR_TARIFA5', 'ORIGEM6', 'DESTINO6',
       'DATA_PARTIDA6', 'DATA_CHEGADA6', 'TARIFA_SEM_ACORDO6', 'TARIFA6',
       'TARIFA_ALTERNATIVA6', 'DATA_ALTERNATIVA6', 'TAXA_EMBARQUE6',
       'VOO6', 'MAIOR_TARIFA6', 'MENOR_TARIFA6'])
df_trecho['Trecho_1'] = df_trecho["ORIGEM1"]+ "/" + df_trecho["DESTINO1"]
df_trecho.head()

          LOCALIZADOR       DATA_APROVACAO  ...  MENOR_TARIFA6  Trecho_1
0  Reserva confirmada  01/07/2021 08:25:00  ...           0,00       NaN
1        Julianderson  01/07/2021 13:14:00  ...           0,00       NaN
2        Julianderson  01/07/2021 13:15:00  ...           0,00       NaN
3        Julianderson  01/07/2021 13:17:00  ...           0,00       NaN
4        Julianderson  01/07/2021 13:17:00  ...           0,00       NaN

[5 rows x 84 columns]

In [879]:
df_trecho2 = pd.DataFrame(df_trecho,columns=['LOCALIZADOR', 'DATA_APROVACAO', 'BILHETE', 'TRECHOS',
       'TRECHOS_CIDADE', 'TOTAL_TARIFA', 'TOTAL_TAXA_EMBARQUE',
       'OUTROS_VALORES', 'TOTAL_GERAL', 'TOTAL_PAGO', 'EMISSÃO/REEMISSÃO',
       'ORIGEM1', 'DESTINO1', 'DATA_PARTIDA1', 'DATA_CHEGADA1', 'TARIFA1',
       'TARIFA_SEM_ACORDO1', 'TARIFA_ALTERNATIVA1', 'DATA_ALTERNATIVA1',
       'TAXA_EMBARQUE1', 'VOO1', 'MAIOR_TARIFA1', 'MENOR_TARIFA1',
       'ORIGEM2', 'DESTINO2', 'DATA_PARTIDA2', 'DATA_CHEGADA2',
       'TARIFA_SEM_ACORDO2', 'TARIFA2', 'TARIFA_ALTERNATIVA2',
       'DATA_ALTERNATIVA2', 'TAXA_EMBARQUE2', 'VOO2', 'MAIOR_TARIFA2',
       'MENOR_TARIFA2', 'ORIGEM3', 'DESTINO3', 'DATA_PARTIDA3',
       'DATA_CHEGADA3', 'TARIFA_SEM_ACORDO3', 'TARIFA3',
       'TARIFA_ALTERNATIVA3', 'DATA_ALTERNATIVA3', 'TAXA_EMBARQUE3',
       'VOO3', 'MAIOR_TARIFA3', 'MENOR_TARIFA3', 'ORIGEM4', 'DESTINO4',
       'DATA_PARTIDA4', 'DATA_CHEGADA4', 'TARIFA_SEM_ACORDO4', 'TARIFA4',
       'TARIFA_ALTERNATIVA4', 'DATA_ALTERNATIVA4', 'TAXA_EMBARQUE4',
       'VOO4', 'MAIOR_TARIFA4', 'MENOR_TARIFA4', 'ORIGEM5', 'DESTINO5',
       'DATA_PARTIDA5', 'DATA_CHEGADA5', 'TARIFA_SEM_ACORDO5', 'TARIFA5',
       'TARIFA_ALTERNATIVA5', 'DATA_ALTERNATIVA5', 'TAXA_EMBARQUE5',
       'VOO5', 'MAIOR_TARIFA5', 'MENOR_TARIFA5', 'ORIGEM6', 'DESTINO6',
       'DATA_PARTIDA6', 'DATA_CHEGADA6', 'TARIFA_SEM_ACORDO6', 'TARIFA6',
       'TARIFA_ALTERNATIVA6', 'DATA_ALTERNATIVA6', 'TAXA_EMBARQUE6',
       'VOO6', 'MAIOR_TARIFA6', 'MENOR_TARIFA6'])
df_trecho['Trecho_2'] = df_trecho["ORIGEM2"]+ "/" + df_trecho["DESTINO2"]
df_trecho.head()

          LOCALIZADOR       DATA_APROVACAO  ...  Trecho_1  Trecho_2
0  Reserva confirmada  01/07/2021 08:25:00  ...       NaN       NaN
1        Julianderson  01/07/2021 13:14:00  ...       NaN       NaN
2        Julianderson  01/07/2021 13:15:00  ...       NaN       NaN
3        Julianderson  01/07/2021 13:17:00  ...       NaN       NaN
4        Julianderson  01/07/2021 13:17:00  ...       NaN       NaN

[5 rows x 85 columns]

In [880]:
df_trecho3 = pd.DataFrame(df_trecho2,columns=['LOCALIZADOR', 'DATA_APROVACAO', 'BILHETE', 'TRECHOS',
       'TRECHOS_CIDADE', 'TOTAL_TARIFA', 'TOTAL_TAXA_EMBARQUE',
       'OUTROS_VALORES', 'TOTAL_GERAL', 'TOTAL_PAGO', 'EMISSÃO/REEMISSÃO',
       'ORIGEM1', 'DESTINO1', 'DATA_PARTIDA1', 'DATA_CHEGADA1', 'TARIFA1',
       'TARIFA_SEM_ACORDO1', 'TARIFA_ALTERNATIVA1', 'DATA_ALTERNATIVA1',
       'TAXA_EMBARQUE1', 'VOO1', 'MAIOR_TARIFA1', 'MENOR_TARIFA1',
       'ORIGEM2', 'DESTINO2', 'DATA_PARTIDA2', 'DATA_CHEGADA2',
       'TARIFA_SEM_ACORDO2', 'TARIFA2', 'TARIFA_ALTERNATIVA2',
       'DATA_ALTERNATIVA2', 'TAXA_EMBARQUE2', 'VOO2', 'MAIOR_TARIFA2',
       'MENOR_TARIFA2', 'ORIGEM3', 'DESTINO3', 'DATA_PARTIDA3',
       'DATA_CHEGADA3', 'TARIFA_SEM_ACORDO3', 'TARIFA3',
       'TARIFA_ALTERNATIVA3', 'DATA_ALTERNATIVA3', 'TAXA_EMBARQUE3',
       'VOO3', 'MAIOR_TARIFA3', 'MENOR_TARIFA3', 'ORIGEM4', 'DESTINO4',
       'DATA_PARTIDA4', 'DATA_CHEGADA4', 'TARIFA_SEM_ACORDO4', 'TARIFA4',
       'TARIFA_ALTERNATIVA4', 'DATA_ALTERNATIVA4', 'TAXA_EMBARQUE4',
       'VOO4', 'MAIOR_TARIFA4', 'MENOR_TARIFA4', 'ORIGEM5', 'DESTINO5',
       'DATA_PARTIDA5', 'DATA_CHEGADA5', 'TARIFA_SEM_ACORDO5', 'TARIFA5',
       'TARIFA_ALTERNATIVA5', 'DATA_ALTERNATIVA5', 'TAXA_EMBARQUE5',
       'VOO5', 'MAIOR_TARIFA5', 'MENOR_TARIFA5', 'ORIGEM6', 'DESTINO6',
       'DATA_PARTIDA6', 'DATA_CHEGADA6', 'TARIFA_SEM_ACORDO6', 'TARIFA6',
       'TARIFA_ALTERNATIVA6', 'DATA_ALTERNATIVA6', 'TAXA_EMBARQUE6',
       'VOO6', 'MAIOR_TARIFA6', 'MENOR_TARIFA6'])
df_trecho['Trecho_3'] = df_trecho["ORIGEM3"]+ "/" + df_trecho["DESTINO3"]
df_trecho.head()

          LOCALIZADOR       DATA_APROVACAO  BILHETE  ...  Trecho_1  Trecho_2  Trecho_3
0  Reserva confirmada  01/07/2021 08:25:00      NaN  ...       NaN       NaN       NaN
1        Julianderson  01/07/2021 13:14:00      NaN  ...       NaN       NaN       NaN
2        Julianderson  01/07/2021 13:15:00      NaN  ...       NaN       NaN       NaN
3        Julianderson  01/07/2021 13:17:00      NaN  ...       NaN       NaN       NaN
4        Julianderson  01/07/2021 13:17:00      NaN  ...       NaN       NaN       NaN

[5 rows x 86 columns]

In [881]:
df_trecho4 = pd.DataFrame(df_trecho3,columns=['LOCALIZADOR', 'DATA_APROVACAO', 'BILHETE', 'TRECHOS',
       'TRECHOS_CIDADE', 'TOTAL_TARIFA', 'TOTAL_TAXA_EMBARQUE',
       'OUTROS_VALORES', 'TOTAL_GERAL', 'TOTAL_PAGO', 'EMISSÃO/REEMISSÃO',
       'ORIGEM1', 'DESTINO1', 'DATA_PARTIDA1', 'DATA_CHEGADA1', 'TARIFA1',
       'TARIFA_SEM_ACORDO1', 'TARIFA_ALTERNATIVA1', 'DATA_ALTERNATIVA1',
       'TAXA_EMBARQUE1', 'VOO1', 'MAIOR_TARIFA1', 'MENOR_TARIFA1',
       'ORIGEM2', 'DESTINO2', 'DATA_PARTIDA2', 'DATA_CHEGADA2',
       'TARIFA_SEM_ACORDO2', 'TARIFA2', 'TARIFA_ALTERNATIVA2',
       'DATA_ALTERNATIVA2', 'TAXA_EMBARQUE2', 'VOO2', 'MAIOR_TARIFA2',
       'MENOR_TARIFA2', 'ORIGEM3', 'DESTINO3', 'DATA_PARTIDA3',
       'DATA_CHEGADA3', 'TARIFA_SEM_ACORDO3', 'TARIFA3',
       'TARIFA_ALTERNATIVA3', 'DATA_ALTERNATIVA3', 'TAXA_EMBARQUE3',
       'VOO3', 'MAIOR_TARIFA3', 'MENOR_TARIFA3', 'ORIGEM4', 'DESTINO4',
       'DATA_PARTIDA4', 'DATA_CHEGADA4', 'TARIFA_SEM_ACORDO4', 'TARIFA4',
       'TARIFA_ALTERNATIVA4', 'DATA_ALTERNATIVA4', 'TAXA_EMBARQUE4',
       'VOO4', 'MAIOR_TARIFA4', 'MENOR_TARIFA4', 'ORIGEM5', 'DESTINO5',
       'DATA_PARTIDA5', 'DATA_CHEGADA5', 'TARIFA_SEM_ACORDO5', 'TARIFA5',
       'TARIFA_ALTERNATIVA5', 'DATA_ALTERNATIVA5', 'TAXA_EMBARQUE5',
       'VOO5', 'MAIOR_TARIFA5', 'MENOR_TARIFA5', 'ORIGEM6', 'DESTINO6',
       'DATA_PARTIDA6', 'DATA_CHEGADA6', 'TARIFA_SEM_ACORDO6', 'TARIFA6',
       'TARIFA_ALTERNATIVA6', 'DATA_ALTERNATIVA6', 'TAXA_EMBARQUE6',
       'VOO6', 'MAIOR_TARIFA6', 'MENOR_TARIFA6'])
df_trecho['Trecho_4'] = df_trecho["ORIGEM4"]+ "/" + df_trecho["DESTINO4"]
df_trecho.head()

          LOCALIZADOR       DATA_APROVACAO  BILHETE  ...  Trecho_2  Trecho_3  Trecho_4
0  Reserva confirmada  01/07/2021 08:25:00      NaN  ...       NaN       NaN       NaN
1        Julianderson  01/07/2021 13:14:00      NaN  ...       NaN       NaN       NaN
2        Julianderson  01/07/2021 13:15:00      NaN  ...       NaN       NaN       NaN
3        Julianderson  01/07/2021 13:17:00      NaN  ...       NaN       NaN       NaN
4        Julianderson  01/07/2021 13:17:00      NaN  ...       NaN       NaN       NaN

[5 rows x 87 columns]

In [882]:
df_trecho5 = pd.DataFrame(df_trecho4,columns=['LOCALIZADOR', 'DATA_APROVACAO', 'BILHETE', 'TRECHOS',
       'TRECHOS_CIDADE', 'TOTAL_TARIFA', 'TOTAL_TAXA_EMBARQUE',
       'OUTROS_VALORES', 'TOTAL_GERAL', 'TOTAL_PAGO', 'EMISSÃO/REEMISSÃO',
       'ORIGEM1', 'DESTINO1', 'DATA_PARTIDA1', 'DATA_CHEGADA1', 'TARIFA1',
       'TARIFA_SEM_ACORDO1', 'TARIFA_ALTERNATIVA1', 'DATA_ALTERNATIVA1',
       'TAXA_EMBARQUE1', 'VOO1', 'MAIOR_TARIFA1', 'MENOR_TARIFA1',
       'ORIGEM2', 'DESTINO2', 'DATA_PARTIDA2', 'DATA_CHEGADA2',
       'TARIFA_SEM_ACORDO2', 'TARIFA2', 'TARIFA_ALTERNATIVA2',
       'DATA_ALTERNATIVA2', 'TAXA_EMBARQUE2', 'VOO2', 'MAIOR_TARIFA2',
       'MENOR_TARIFA2', 'ORIGEM3', 'DESTINO3', 'DATA_PARTIDA3',
       'DATA_CHEGADA3', 'TARIFA_SEM_ACORDO3', 'TARIFA3',
       'TARIFA_ALTERNATIVA3', 'DATA_ALTERNATIVA3', 'TAXA_EMBARQUE3',
       'VOO3', 'MAIOR_TARIFA3', 'MENOR_TARIFA3', 'ORIGEM4', 'DESTINO4',
       'DATA_PARTIDA4', 'DATA_CHEGADA4', 'TARIFA_SEM_ACORDO4', 'TARIFA4',
       'TARIFA_ALTERNATIVA4', 'DATA_ALTERNATIVA4', 'TAXA_EMBARQUE4',
       'VOO4', 'MAIOR_TARIFA4', 'MENOR_TARIFA4', 'ORIGEM5', 'DESTINO5',
       'DATA_PARTIDA5', 'DATA_CHEGADA5', 'TARIFA_SEM_ACORDO5', 'TARIFA5',
       'TARIFA_ALTERNATIVA5', 'DATA_ALTERNATIVA5', 'TAXA_EMBARQUE5',
       'VOO5', 'MAIOR_TARIFA5', 'MENOR_TARIFA5', 'ORIGEM6', 'DESTINO6',
       'DATA_PARTIDA6', 'DATA_CHEGADA6', 'TARIFA_SEM_ACORDO6', 'TARIFA6',
       'TARIFA_ALTERNATIVA6', 'DATA_ALTERNATIVA6', 'TAXA_EMBARQUE6',
       'VOO6', 'MAIOR_TARIFA6', 'MENOR_TARIFA6'])
df_trecho['Trecho_5'] = df_trecho["ORIGEM5"]+ "/" + df_trecho["DESTINO5"]
df_trecho.head()

          LOCALIZADOR       DATA_APROVACAO  BILHETE  ...  Trecho_3  Trecho_4  Trecho_5
0  Reserva confirmada  01/07/2021 08:25:00      NaN  ...       NaN       NaN       NaN
1        Julianderson  01/07/2021 13:14:00      NaN  ...       NaN       NaN       NaN
2        Julianderson  01/07/2021 13:15:00      NaN  ...       NaN       NaN       NaN
3        Julianderson  01/07/2021 13:17:00      NaN  ...       NaN       NaN       NaN
4        Julianderson  01/07/2021 13:17:00      NaN  ...       NaN       NaN       NaN

[5 rows x 88 columns]

In [883]:
df_trecho6 = pd.DataFrame(df_trecho5,columns=['LOCALIZADOR', 'DATA_APROVACAO', 'BILHETE', 'TRECHOS',
       'TRECHOS_CIDADE', 'TOTAL_TARIFA', 'TOTAL_TAXA_EMBARQUE',
       'OUTROS_VALORES', 'TOTAL_GERAL', 'TOTAL_PAGO', 'EMISSÃO/REEMISSÃO',
       'ORIGEM1', 'DESTINO1', 'DATA_PARTIDA1', 'DATA_CHEGADA1', 'TARIFA1',
       'TARIFA_SEM_ACORDO1', 'TARIFA_ALTERNATIVA1', 'DATA_ALTERNATIVA1',
       'TAXA_EMBARQUE1', 'VOO1', 'MAIOR_TARIFA1', 'MENOR_TARIFA1',
       'ORIGEM2', 'DESTINO2', 'DATA_PARTIDA2', 'DATA_CHEGADA2',
       'TARIFA_SEM_ACORDO2', 'TARIFA2', 'TARIFA_ALTERNATIVA2',
       'DATA_ALTERNATIVA2', 'TAXA_EMBARQUE2', 'VOO2', 'MAIOR_TARIFA2',
       'MENOR_TARIFA2', 'ORIGEM3', 'DESTINO3', 'DATA_PARTIDA3',
       'DATA_CHEGADA3', 'TARIFA_SEM_ACORDO3', 'TARIFA3',
       'TARIFA_ALTERNATIVA3', 'DATA_ALTERNATIVA3', 'TAXA_EMBARQUE3',
       'VOO3', 'MAIOR_TARIFA3', 'MENOR_TARIFA3', 'ORIGEM4', 'DESTINO4',
       'DATA_PARTIDA4', 'DATA_CHEGADA4', 'TARIFA_SEM_ACORDO4', 'TARIFA4',
       'TARIFA_ALTERNATIVA4', 'DATA_ALTERNATIVA4', 'TAXA_EMBARQUE4',
       'VOO4', 'MAIOR_TARIFA4', 'MENOR_TARIFA4', 'ORIGEM5', 'DESTINO5',
       'DATA_PARTIDA5', 'DATA_CHEGADA5', 'TARIFA_SEM_ACORDO5', 'TARIFA5',
       'TARIFA_ALTERNATIVA5', 'DATA_ALTERNATIVA5', 'TAXA_EMBARQUE5',
       'VOO5', 'MAIOR_TARIFA5', 'MENOR_TARIFA5', 'ORIGEM6', 'DESTINO6',
       'DATA_PARTIDA6', 'DATA_CHEGADA6', 'TARIFA_SEM_ACORDO6', 'TARIFA6',
       'TARIFA_ALTERNATIVA6', 'DATA_ALTERNATIVA6', 'TAXA_EMBARQUE6',
       'VOO6', 'MAIOR_TARIFA6', 'MENOR_TARIFA6'])
df_trecho['Trecho_6'] = df_trecho["ORIGEM6"]+ "/" + df_trecho["DESTINO6"]
df_trecho.head()

          LOCALIZADOR       DATA_APROVACAO  BILHETE  ...  Trecho_4  Trecho_5  Trecho_6
0  Reserva confirmada  01/07/2021 08:25:00      NaN  ...       NaN       NaN       NaN
1        Julianderson  01/07/2021 13:14:00      NaN  ...       NaN       NaN       NaN
2        Julianderson  01/07/2021 13:15:00      NaN  ...       NaN       NaN       NaN
3        Julianderson  01/07/2021 13:17:00      NaN  ...       NaN       NaN       NaN
4        Julianderson  01/07/2021 13:17:00      NaN  ...       NaN       NaN       NaN

[5 rows x 89 columns]

In [884]:
#faz um merge usando o localizador como referência
fusao_plan = pd.merge(df_stur,df_trecho, how='left', left_on=['Localizador'],right_on=['LOCALIZADOR'])

In [885]:
#insere novas colunas que vão ficar em branco
fusao_plan.insert(loc=1, column='data_chegada_txt',value=" ")
fusao_plan.insert(loc=2, column='taxa_fee',value=" ")
fusao_plan.insert(loc=3, column='taxa_fee_paga',value=" ")
fusao_plan.insert(loc=4, column='fatura_paga',value=" ")
fusao_plan.insert(loc=5, column='comissao',value=" ")
fusao_plan.insert(loc=6, column='taxa_fee_reembolso',value=" ")
fusao_plan.insert(loc=7, column='classe_trecho_1',value=" ")
fusao_plan.insert(loc=8, column='classe_trecho_2',value=" ")
fusao_plan.insert(loc=9, column='classe_trecho_3',value=" ")
fusao_plan.insert(loc=10, column='classe_trecho_4',value=" ")
fusao_plan.insert(loc=11, column='classe_trecho_5',value=" ")
fusao_plan.insert(loc=12, column='classe_trecho_6',value=" ")
fusao_plan.head()

  Dt. Desembarque data_chegada_txt taxa_fee  ... Trecho_4 Trecho_5 Trecho_6
0      2021-09-18                            ...      NaN      NaN      NaN
1             NaT                            ...      NaN      NaN      NaN
2      2021-07-28                            ...      NaN      NaN      NaN
3             NaT                            ...      NaN      NaN      NaN
4      2021-08-30                            ...      NaN      NaN      NaN

[5 rows x 162 columns]

In [886]:
fusao_plan.columns.values

array(['Dt. Desembarque', 'data_chegada_txt', 'taxa_fee', 'taxa_fee_paga',
       'fatura_paga', 'comissao', 'taxa_fee_reembolso', 'classe_trecho_1',
       'classe_trecho_2', 'classe_trecho_3', 'classe_trecho_4',
       'classe_trecho_5', 'classe_trecho_6', 'Matrícula',
       'Nome [Passageiro]', 'Cia [Trecho]', 'Fornecedor do Serviço',
       'Sigla Cia. Aérea', 'Localizador', 'Bilhete', 'Data Emissão',
       'Class.Produto', 'Valor [Recebimento]', 'Tarifa [R$] Cliente',
       'Tx.Embarque', 'Tx.Extra', 'Tarifa Cheia Cliente', 'N° Viagem',
       'N°.Reg.Gov.', 'Fatura [Recebimento]',
       'C.Custo Cliente (Descrição)', 'Tx.Sucesso', 'Taxa DU Líquida',
       'Forma Cartão [Recebimento]', 'Comissão Emissor Externo',
       'Economia Realizada', 'Rota Completa', 'Data Saída [Trecho]',
       'Valor Acordo', 'Valor Comis.AGT.', 'Voos da Rota',
       'Data Cancelamento', 'Valor Comis.Rec.', 'Valor CPMF',
       'Voo [Trecho]', 'Data Devolução', 'Valor Câmbio',
       'Valor Câmbio Fornec', 'Data Exp. Documento', 'Valor Comis.Rep.',
       'Valor Diária Balcão [Apartamento]', 'Cupom [Trecho]',
       'Data Nascimento [Passageiro]', 'Valor Apli. Rec.',
       'Valor Diária [Apartamento]', 'Cód. tarifa [Trecho]',
       'Data Nascimento Pax', 'Valor ISS Aplicado.',
       'Valor Geral Taxas (Cliente)', 'Classe [Trecho]', 'Classe do Vôo',
       'Classes da Rota', 'Regime', 'CPF Passageiro',
       'Cód. tarifa da rota', 'Cód. Autorização Cartão [Recebimento]',
       'Autorizador', 'Atividade', 'Antecedência', 'Data Retirada',
       'Fee Pagar', 'Motivo da Viagem', 'Número Pedido', 'LOCALIZADOR',
       'DATA_APROVACAO', 'BILHETE', 'TRECHOS', 'TRECHOS_CIDADE',
       'TOTAL_TARIFA', 'TOTAL_TAXA_EMBARQUE', 'OUTROS_VALORES',
       'TOTAL_GERAL', 'TOTAL_PAGO', 'EMISSÃO/REEMISSÃO', 'ORIGEM1',
       'DESTINO1', 'DATA_PARTIDA1', 'DATA_CHEGADA1', 'TARIFA1',
       'TARIFA_SEM_ACORDO1', 'TARIFA_ALTERNATIVA1', 'DATA_ALTERNATIVA1',
       'TAXA_EMBARQUE1', 'VOO1', 'MAIOR_TARIFA1', 'MENOR_TARIFA1',
       'ORIGEM2', 'DESTINO2', 'DATA_PARTIDA2', 'DATA_CHEGADA2',
       'TARIFA_SEM_ACORDO2', 'TARIFA2', 'TARIFA_ALTERNATIVA2',
       'DATA_ALTERNATIVA2', 'TAXA_EMBARQUE2', 'VOO2', 'MAIOR_TARIFA2',
       'MENOR_TARIFA2', 'ORIGEM3', 'DESTINO3', 'DATA_PARTIDA3',
       'DATA_CHEGADA3', 'TARIFA_SEM_ACORDO3', 'TARIFA3',
       'TARIFA_ALTERNATIVA3', 'DATA_ALTERNATIVA3', 'TAXA_EMBARQUE3',
       'VOO3', 'MAIOR_TARIFA3', 'MENOR_TARIFA3', 'ORIGEM4', 'DESTINO4',
       'DATA_PARTIDA4', 'DATA_CHEGADA4', 'TARIFA_SEM_ACORDO4', 'TARIFA4',
       'TARIFA_ALTERNATIVA4', 'DATA_ALTERNATIVA4', 'TAXA_EMBARQUE4',
       'VOO4', 'MAIOR_TARIFA4', 'MENOR_TARIFA4', 'ORIGEM5', 'DESTINO5',
       'DATA_PARTIDA5', 'DATA_CHEGADA5', 'TARIFA_SEM_ACORDO5', 'TARIFA5',
       'TARIFA_ALTERNATIVA5', 'DATA_ALTERNATIVA5', 'TAXA_EMBARQUE5',
       'VOO5', 'MAIOR_TARIFA5', 'MENOR_TARIFA5', 'ORIGEM6', 'DESTINO6',
       'DATA_PARTIDA6', 'DATA_CHEGADA6', 'TARIFA_SEM_ACORDO6', 'TARIFA6',
       'TARIFA_ALTERNATIVA6', 'DATA_ALTERNATIVA6', 'TAXA_EMBARQUE6',
       'VOO6', 'MAIOR_TARIFA6', 'MENOR_TARIFA6', 'Trecho_1', 'Trecho_2',
       'Trecho_3', 'Trecho_4', 'Trecho_5', 'Trecho_6'], dtype=object)

In [887]:
fusao_plan[['Data_Aprovacao', 'Hora_Aprovacao']] = fusao_plan['DATA_APROVACAO'].str.split(' ', expand=True)

In [888]:
fusao_plan['Data Emissão'] = pd.to_datetime(fusao_plan['Data Emissão'])

In [889]:
fusao_plan['Data Saída [Trecho]'] = pd.to_datetime(fusao_plan['Data Saída [Trecho]'])

In [890]:
fusao_plan['Data Emissão'] = fusao_plan['Data Emissão'].dt.strftime('%d/%m/%Y')

In [891]:
fusao_plan['Data Saída [Trecho]'] = fusao_plan['Data Saída [Trecho]'].dt.strftime('%m/%d/%Y')

In [892]:
#fusao_plan['Data Saída [Trecho]'] = fusao_plan['Data Saída [Trecho]'].apply(lambda _: str(_))

In [896]:
fusao_plan['LOCALIZADOR'].value_counts()

TVLKOH    2
NBTRVL    2
SEB1QS    1
PMN4XX    1
OMI72U    1
MEYCRS    1
CG81TZ    1
YKVCGS    1
HB1P6Y    1
YKNJPQ    1
UCUEPY    1
JUAKXV    1
SHSH5G    1
VL12SA    1
VHKMEX    1
GBMCPY    1
ALBHNX    1
RH2BSZ    1
XWFZ5R    1
LMF59U    1
FJMEMA    1
LHD16G    1
YEN12C    1
QKF4KA    1
BMAEMU    1
SLVBMK    1
SK8EQQ    1
NNIMGE    1
VJBKPT    1
OKGWSA    1
ZK85VD    1
QN9HVH    1
VBTIVJ    1
DMH4XH    1
FPQRUF    1
Name: LOCALIZADOR, dtype: int64

In [897]:
#colunas que estão com os ítens selecionados
colunas_selecionadas = ["data_chegada_txt",
"Matrícula",
"Nome [Passageiro]",
"Cia [Trecho]",
"Fornecedor do Serviço", 
"Sigla Cia. Aérea",
"Localizador",
"Bilhete",
"Data Emissão",
"Class.Produto",
"Valor [Recebimento]",
"Tarifa [R$] Cliente",
"Tx.Embarque",
"Tx.Extra",
"Tarifa Cheia Cliente",
"Número Pedido",
"N°.Reg.Gov.",
"Fatura [Recebimento]",
"C.Custo Cliente (Descrição)",
"Tx.Sucesso",
"Taxa DU Líquida",
"Forma Cartão [Recebimento]",
"Comissão Emissor Externo",
"Economia Realizada",
"Trecho_1",
"Data Saída [Trecho]",
"Valor Acordo",
"Valor Comis.AGT.",
"Trecho_2",
"Data Cancelamento",
"Valor Comis.Rec.",
"Valor CPMF",
"Trecho_3",
"Data Devolução",
"Valor Câmbio",
"Valor Câmbio Fornec",
"Trecho_4",
"Valor Comis.Rep.",
"Valor Diária Balcão [Apartamento]",
"Cupom [Trecho]",
"Trecho_5",
"Valor Apli. Rec.",
"Valor Diária [Apartamento]",
"Cód. tarifa [Trecho]",
"Trecho_6",
"Valor ISS Aplicado.",
"Valor Geral Taxas (Cliente)",
"Classe [Trecho]",
"Classe do Vôo",
"Classes da Rota",
"Regime",
"CPF Passageiro",
"Cód. tarifa da rota",
"Cód. Autorização Cartão [Recebimento]",
"CÓDIGO_AUTORIZADOR",
"Data_Aprovacao", 
"Hora_Aprovacao", 
"taxa_fee_reembolso",
"Motivo da Viagem",
"Autorizador", "Nome_Autorizador", ]

In [898]:
#filtra e organiza os dados pelas colunas que foram passadas
dados_separados = fusao_plan.filter(items=colunas_selecionadas)

In [899]:
dados_separados_aereo = pd.merge(dados_separados,df_autorizador, how='left', left_on=['Autorizador'],right_on=['Nome_Autorizador'])
dados_separados_aereo.head()

  data_chegada_txt Matrícula  ... CÓDIGO_AUTORIZADOR      Nome_Autorizador
0                      22127  ...              19657  ALEXANDRE PELISSARI
1                        NaN  ...                NaN                   NaN
2                      22135  ...                NaN                   NaN
3                        NaN  ...                NaN                   NaN
4                      21341  ...                NaN                   NaN

[5 rows x 61 columns]

In [900]:
#colunas que estão com os ítens selecionados
colunas_selecionadas_aereo2 = ["data_chegada_txt",
"Matrícula",
"Nome [Passageiro]",
"Cia [Trecho]",
"Fornecedor do Serviço", 
"Sigla Cia. Aérea",
"Localizador",
"Bilhete",
"Data Emissão",
"Class.Produto",
"Valor [Recebimento]",
"Tarifa [R$] Cliente",
"Tx.Embarque",
"Tx.Extra",
"Tarifa Cheia Cliente",
"Número Pedido",
"N°.Reg.Gov.",
"Fatura [Recebimento]",
"C.Custo Cliente (Descrição)",
"Tx.Sucesso",
"Taxa DU Líquida",
"Forma Cartão [Recebimento]",
"Comissão Emissor Externo",
"Economia Realizada",
"Trecho_1",
"Data Saída [Trecho]",
"Valor Acordo",
"Valor Comis.AGT.",
"Trecho_2",
"Data Cancelamento",
"Valor Comis.Rec.",
"Valor CPMF",
"Trecho_3",
"Data Devolução",
"Valor Câmbio",
"Valor Câmbio Fornec",
"Trecho_4",
"Valor Comis.Rep.",
"Valor Diária Balcão [Apartamento]",
"Cupom [Trecho]",
"Trecho_5",
"Valor Apli. Rec.",
"Valor Diária [Apartamento]",
"Cód. tarifa [Trecho]",
"Trecho_6",
"Valor ISS Aplicado.",
"Valor Geral Taxas (Cliente)",
"Classe [Trecho]",
"Classe do Vôo",
"Classes da Rota",
"Regime",
"CPF Passageiro",
"Cód. tarifa da rota",
"Cód. Autorização Cartão [Recebimento]",
 "CÓDIGO_AUTORIZADOR",
"Data_Aprovacao", 
"Hora_Aprovacao", 
"taxa_fee_reembolso",
"Motivo da Viagem",
 ]

In [901]:
#filtra e organiza os dados pelas colunas que foram passadas
dados_separados_aereo2 = dados_separados_aereo.filter(items=colunas_selecionadas_aereo2)

In [902]:
#colunas que estão com os ítens selecionados
#colunas_selecionadas = ['Dt. Desembarque', 'Matrícula', 'Nome [Passageiro]',
#                        'Cia [Trecho]', 'Fornecedor do Serviço', 'Sigla Cia. Aérea',
#                        'Localizador', 'Bilhete', 'Data Emissão', 'Class.Produto',
#                        'Valor [Recebimento]', 'Tarifa [R$] Cliente', 'Tx.Embarque',
#                        'Tx.Extra', 'Tarifa Cheia Cliente', 'Número Pedido', 'N°.Reg.Gov.',
#                        'Fatura [Recebimento]', 'C.Custo Cliente (Descrição)', 'Tx.Sucesso',
#                        'Taxa DU Líquida', 'Forma Cartão [Recebimento]', 'Comissão Emissor Externo',
#                        'Economia Realizada', 'Rota Completa', 'Data Saída [Trecho]', 'Valor Acordo',
#                        'Valor Comis.AGT.', 'Voos da Rota', 'Data Cancelamento', 'Valor Comis.Rec.',
#                        'Valor CPMF', 'Voo [Trecho]', 'Data Devolução', 'Valor Câmbio', 'Valor Câmbio Fornec',
#                        'Data Exp. Documento', 'Valor Comis.Rep.', 'Valor Diária Balcão [Apartamento]',
#                        'Cupom [Trecho]', 'Data Nascimento [Passageiro]', 'Valor Apli. Rec.',
#                        'Valor Diária [Apartamento]', 'Cód. tarifa [Trecho]', 'Data Nascimento Pax',
#                        'Valor ISS Aplicado.', 'Valor Geral Taxas (Cliente)', 'Classe [Trecho]',
#                        'Classe do Vôo', 'Classes da Rota', 'Regime', 'CPF Passageiro',
#                        'Cód. tarifa da rota', 'Cód. Autorização Cartão [Recebimento]',
#                        'Autorizador', 'Atividade', 'Antecedência', 'Data Retirada',
#                        'Fee Pagar', 'Motivo da Viagem', 'Trecho_1', 'Trecho_2',
#       'Trecho_3', 'Trecho_4', 'Trecho_5', 'Trecho_6', 'Data_Aprovacao',
#       'Hora_Aprovacao', 'Data_Saída', 'Hora_Saída', 'Data_Emissão',
#       'Hora_Emissão']

In [903]:
dados_separados_aereo2.columns.values

array(['data_chegada_txt', 'Matrícula', 'Nome [Passageiro]',
       'Cia [Trecho]', 'Fornecedor do Serviço', 'Sigla Cia. Aérea',
       'Localizador', 'Bilhete', 'Data Emissão', 'Class.Produto',
       'Valor [Recebimento]', 'Tarifa [R$] Cliente', 'Tx.Embarque',
       'Tx.Extra', 'Tarifa Cheia Cliente', 'Número Pedido', 'N°.Reg.Gov.',
       'Fatura [Recebimento]', 'C.Custo Cliente (Descrição)',
       'Tx.Sucesso', 'Taxa DU Líquida', 'Forma Cartão [Recebimento]',
       'Comissão Emissor Externo', 'Economia Realizada', 'Trecho_1',
       'Data Saída [Trecho]', 'Valor Acordo', 'Valor Comis.AGT.',
       'Trecho_2', 'Data Cancelamento', 'Valor Comis.Rec.', 'Valor CPMF',
       'Trecho_3', 'Data Devolução', 'Valor Câmbio',
       'Valor Câmbio Fornec', 'Trecho_4', 'Valor Comis.Rep.',
       'Valor Diária Balcão [Apartamento]', 'Cupom [Trecho]', 'Trecho_5',
       'Valor Apli. Rec.', 'Valor Diária [Apartamento]',
       'Cód. tarifa [Trecho]', 'Trecho_6', 'Valor ISS Aplicado.',
       'Valor Geral Taxas (Cliente)', 'Classe [Trecho]', 'Classe do Vôo',
       'Classes da Rota', 'Regime', 'CPF Passageiro',
       'Cód. tarifa da rota', 'Cód. Autorização Cartão [Recebimento]',
       'CÓDIGO_AUTORIZADOR', 'Data_Aprovacao', 'Hora_Aprovacao',
       'taxa_fee_reembolso', 'Motivo da Viagem'], dtype=object)

In [904]:
#renomear todas as colunas aereo
dados_separados_aereo2.rename(columns={
"data_chegada_txt": "data_chegada_txt",
"Matrícula": "mat viajante",
"Nome [Passageiro]": "nome viajante",
"Cia [Trecho]": "cod cia",
"Fornecedor do Serviço": "nome cia ", 
"Sigla Cia. Aérea": "sigla cia ",
"Localizador": "localizador ",
"Bilhete": "n bilhete ",
"Data Emissão": "data emissao",
"Class.Produto": "tipo",
"Valor [Recebimento]": "valor pago",
"Tarifa [R$] Cliente": "valor tarifa",
"Tx.Embarque": "valor taxa",
"Tx.Extra": "valor outras",
"Tarifa Cheia Cliente": "valor tarifa cheia",
"Número Pedido": "n_req",
"N°.Reg.Gov.": "n_req_sap",
"Fatura [Recebimento]": "n fatura",
"C.Custo Cliente (Descrição)": "destinacao_contabil",
"Tx.Sucesso": "taxa fee",
"Taxa DU Líquida": "taxa fee_paga",
"Forma Cartão [Recebimento]": "fatura_paga",
"Comissão Emissor Externo": "comissao",
"Economia Realizada": "economia",
"Trecho_1": "trecho 1",
"Data Saída [Trecho]": "data trecho 1",
"Valor Acordo": "valor_tarifa_trecho_1",
"Valor Comis.AGT.": "valor_taxa_trecho_1",
"Trecho_2": "trecho 2",
"Data Cancelamento": "data trecho 2",
"Valor Comis.Rec.": "valor_tarifa_trecho_2",
"Valor CPMF": "valor_taxa_trecho_2",
"Trecho_3": "trecho 3",
"Data Devolução": "data trecho 3",
"Valor Câmbio": "valor_tarifa_trecho_3",
"Valor Câmbio Fornec": "valor_taxa_trecho_3",
"Trecho_4": "trecho 4",
"Valor Comis.Rep.": "data trecho 4",
"Valor Diária Balcão [Apartamento]": "valor_tarifa_trecho_4",
"Cupom [Trecho]": "valor_taxa_trecho_4",
"Trecho_5": "trecho 5",
"Valor Apli. Rec.": "data trecho 5",
"Valor Diária [Apartamento]": "valor_tarifa_trecho_5",
"Cód. tarifa [Trecho]": "valor_taxa_trecho_5",
"Trecho_6": "trecho 6",
"Valor ISS Aplicado.": "data trecho 6",
"Valor Geral Taxas (Cliente)": "valor_tarifa_trecho_6",
"Classe [Trecho]": "valor_taxa_trecho_6",
"Classe do Vôo": "classe_trecho_1",
"Classes da Rota": "classe_trecho_2",
"Regime": "classe_trecho_3",
"CPF Passageiro": "classe_trecho_4",
"Cód. tarifa da rota": "classe_trecho_5",
"Cód. Autorização Cartão [Recebimento]": "classe_trecho_6",
"CÓDIGO_AUTORIZADOR": "mat aprovador",
"Data_Aprovacao": "data aprovacao",
"Hora_Aprovacao": "hora aprovacao", 
"taxa_fee_reembolso": "taxa fee reembolso",
"Motivo da Viagem": "justificativa de viagem",
}, inplace=True)

In [905]:
dados_separados_aereo2.columns.values

array(['data_chegada_txt', 'mat viajante', 'nome viajante', 'cod cia',
       'nome cia ', 'sigla cia ', 'localizador ', 'n bilhete ',
       'data emissao', 'tipo', 'valor pago', 'valor tarifa', 'valor taxa',
       'valor outras', 'valor tarifa cheia', 'n_req', 'n_req_sap',
       'n fatura', 'destinacao_contabil', 'taxa fee', 'taxa fee_paga',
       'fatura_paga', 'comissao', 'economia', 'trecho 1', 'data trecho 1',
       'valor_tarifa_trecho_1', 'valor_taxa_trecho_1', 'trecho 2',
       'data trecho 2', 'valor_tarifa_trecho_2', 'valor_taxa_trecho_2',
       'trecho 3', 'data trecho 3', 'valor_tarifa_trecho_3',
       'valor_taxa_trecho_3', 'trecho 4', 'data trecho 4',
       'valor_tarifa_trecho_4', 'valor_taxa_trecho_4', 'trecho 5',
       'data trecho 5', 'valor_tarifa_trecho_5', 'valor_taxa_trecho_5',
       'trecho 6', 'data trecho 6', 'valor_tarifa_trecho_6',
       'valor_taxa_trecho_6', 'classe_trecho_1', 'classe_trecho_2',
       'classe_trecho_3', 'classe_trecho_4', 'classe_trecho_5',
       'classe_trecho_6', 'mat aprovador', 'data aprovacao',
       'hora aprovacao', 'taxa fee reembolso', 'justificativa de viagem'],
      dtype=object)

In [906]:
#PLANILHA RELATÓRIO - colunas que estão com os ítens selecionados
colunas_selecionadas_relatorio = ['n fatura', 'n_req_sap', 'destinacao_contabil', 'valor pago',   ]

In [907]:
#PLANILHA RELATÓRIO - filtra e organiza os dados pelas colunas que foram passadas
dados_separados_aereo3 = dados_separados_aereo2.filter(items=colunas_selecionadas_relatorio)

In [908]:
dados_separados_aereo3.to_excel('Relatório.xlsx', index=False)

In [909]:
dados_separados_aereo2.columns.values

array(['data_chegada_txt', 'mat viajante', 'nome viajante', 'cod cia',
       'nome cia ', 'sigla cia ', 'localizador ', 'n bilhete ',
       'data emissao', 'tipo', 'valor pago', 'valor tarifa', 'valor taxa',
       'valor outras', 'valor tarifa cheia', 'n_req', 'n_req_sap',
       'n fatura', 'destinacao_contabil', 'taxa fee', 'taxa fee_paga',
       'fatura_paga', 'comissao', 'economia', 'trecho 1', 'data trecho 1',
       'valor_tarifa_trecho_1', 'valor_taxa_trecho_1', 'trecho 2',
       'data trecho 2', 'valor_tarifa_trecho_2', 'valor_taxa_trecho_2',
       'trecho 3', 'data trecho 3', 'valor_tarifa_trecho_3',
       'valor_taxa_trecho_3', 'trecho 4', 'data trecho 4',
       'valor_tarifa_trecho_4', 'valor_taxa_trecho_4', 'trecho 5',
       'data trecho 5', 'valor_tarifa_trecho_5', 'valor_taxa_trecho_5',
       'trecho 6', 'data trecho 6', 'valor_tarifa_trecho_6',
       'valor_taxa_trecho_6', 'classe_trecho_1', 'classe_trecho_2',
       'classe_trecho_3', 'classe_trecho_4', 'classe_trecho_5',
       'classe_trecho_6', 'mat aprovador', 'data aprovacao',
       'hora aprovacao', 'taxa fee reembolso', 'justificativa de viagem'],
      dtype=object)

In [911]:
dados_separados_aereo2[['num_ped1', 'num_ped2']] = dados_separados_aereo2['n_req'].str.split('-', expand=True)

In [912]:
#colunas que estão com os ítens selecionados
colunas_selecionadas_aereo_depois = ['data_chegada_txt', 'mat viajante', 'nome viajante', 'cod cia',
       'nome cia ', 'sigla cia ', 'localizador ', 'n bilhete ',
       'data emissao', 'tipo', 'valor pago', 'valor tarifa', 'valor taxa',
       'valor outras', 'valor tarifa cheia', 'num_ped1', 'n_req_sap',
       'n fatura', 'destinacao_contabil', 'taxa fee', 'taxa fee_paga',
       'fatura_paga', 'comissao', 'economia', 'trecho 1', 'data trecho 1',
       'valor_tarifa_trecho_1', 'valor_taxa_trecho_1', 'trecho 2',
       'data trecho 2', 'valor_tarifa_trecho_2', 'valor_taxa_trecho_2',
       'trecho 3', 'data trecho 3', 'valor_tarifa_trecho_3',
       'valor_taxa_trecho_3', 'trecho 4', 'data trecho 4',
       'valor_tarifa_trecho_4', 'valor_taxa_trecho_4', 'trecho 5',
       'data trecho 5', 'valor_tarifa_trecho_5', 'valor_taxa_trecho_5',
       'trecho 6', 'data trecho 6', 'valor_tarifa_trecho_6',
       'valor_taxa_trecho_6', 'classe_trecho_1', 'classe_trecho_2',
       'classe_trecho_3', 'classe_trecho_4', 'classe_trecho_5',
       'classe_trecho_6', 'mat aprovador', 'data aprovacao',
       'hora aprovacao', 'taxa fee reembolso', 'justificativa de viagem'
 ]

In [913]:
#filtra e organiza os dados pelas colunas que foram passadas
dados_separados_aereo2 = dados_separados_aereo2.filter(items=colunas_selecionadas_aereo_depois)

In [914]:
#renomear todas as colunas aereo
dados_separados_aereo2.rename(columns={
"data_chegada_txt": "data_chegada_txt",
"mat viajante": "mat viajante",
"nome viajante": "nome viajante",
"cod cia": "cod cia",
"nome cia": "nome cia", 
"sigla cia": "sigla cia",
"localizador": "localizador ",
"n bilhete": "n bilhete ",
"data emissao": "data emissao",
"tipo": "tipo",
"valor pago": "valor pago",
"valor tarifa": "valor tarifa",
"valor taxa": "valor taxa",
"valor outras": "valor outras",
"valor tarifa cheia": "valor tarifa cheia",
"num_ped1": "n_req",
"n_req_sap": "n_req_sap",
"n fatura": "n fatura",
"destinacao_contabil": "destinacao_contabil",
"taxa fee": "taxa fee",
"taxa fee_paga": "taxa fee_paga",
"fatura_paga": "fatura_paga",
"comissao": "comissao",
"economia": "economia",
"trecho 1": "trecho 1",
"data trecho 1": "data trecho 1",
"valor_tarifa_trecho_1": "valor_tarifa_trecho_1",
"valor_taxa_trecho_1": "valor_taxa_trecho_1",
"trecho 2": "trecho 2",
"data trecho 2": "data trecho 2",
"valor_tarifa_trecho_2": "valor_tarifa_trecho_2",
"valor_taxa_trecho_2": "valor_taxa_trecho_2",
"trecho 3": "trecho 3",
"data trecho 3": "data trecho 3",
"valor_tarifa_trecho_3": "valor_tarifa_trecho_3",
"valor_taxa_trecho_3": "valor_taxa_trecho_3",
"trecho 4": "trecho 4",
"data trecho 4": "data trecho 4",
"valor_tarifa_trecho_4": "valor_tarifa_trecho_4",
"valor_taxa_trecho_4": "valor_taxa_trecho_4",
"trecho 5": "trecho 5",
"data trecho 5": "data trecho 5",
"valor_tarifa_trecho_5": "valor_tarifa_trecho_5",
"valor_taxa_trecho_5": "valor_taxa_trecho_5",
"trecho 6": "trecho 6",
"data trecho 6": "data trecho 6",
"valor_tarifa_trecho_6": "valor_tarifa_trecho_6",
"valor_taxa_trecho_6": "valor_taxa_trecho_6",
"classe_trecho_1": "classe_trecho_1",
"classe_trecho_2": "classe_trecho_2",
"classe_trecho_3": "classe_trecho_3",
"classe_trecho_4": "classe_trecho_4",
"classe_trecho_5": "classe_trecho_5",
"classe_trecho_6": "classe_trecho_6",
"mat aprovador": "mat aprovador",
"data aprovacao": "data aprovacao",
"hora aprovacao": "hora aprovacao", 
"taxa fee reembolso": "taxa fee reembolso",
"justificativa de viagem": "justificativa de viagem",
}, inplace=True)

In [915]:
dados_separados_aereo2.to_excel('PLANILHA_AEREO.xlsx', index=False)

In [916]:
#dados_separados_aereo3.to_excel('RELATÓRIO.xlsx', index=False)

In [917]:
#df_autorizador.to_dict()

In [918]:
#dados_separados['CÓDIGO_AUT'] = [df_autorizador[resp] for resp in dados_separados.Autorizador]

In [919]:
#df_autorizador['22659']